name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *' # At minute 0 past every 12th hour
    #- cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ github.token }}
          repo: compose-rich-editor
          owner: scto
          base: main
          head: main
          merge_method:	merge
